src/modes/index.js, src/modes/qa.mode.js, src/webloader.js
=> feat: cross browser qa

src/tests/webloader.test.js, src/webloader.js
=> fix: firefox not running asset manager

src/modes/qa.mode.js, src/webloader.js
RKT-7588
Arrow functions are not supported by IE
=> fix: ie does not support arrow functions

package-lock.json, package.json, src/all.js, src/index.js, src/tests/all.test.js, src/tests/index.test.js
move promises to the execution of the javascript variant
RKT-7590
=> fix: ie11 failing

e2e/tests/apply-changes/apply-changes.test.ts
remove promise from variant
RKT-7590
=> fix: updating e2e test

.eslintrc.json, .github/workflows/nightly.yml, e2e/launcher/browsers.js, e2e/launcher/run-tests.js, e2e/launcher/start.js, e2e/tests/apply-changes/index.html, e2e/tests/basic/index.html, package-lock.json, package.json, scripts/e2e-test.sh
creating PRs to test running with actions
=> chore: e2e browserstack

.github/workflows/escalated-push.yml, src/tests/mocks/document.mock.js
only master is used for repository dispatches
=> chore: updating workflow on master

.github/workflows/escalated-pull-request-merge.yml, .github/workflows/nightly.yml
testing that we get the right commit hash
=> chore: allow escalated pull request merge to run on master

package-lock.json, package.json
=> fix: upgrade version of javascript-sdk

src/webloader.js
=> fix: web.url is not updated on angular route changes

README.md, src/index.js, src/tests/index.test.js, src/webloader.js
=> chore: make timeout configurable

package-lock.json, package.json
=> fix: bump version of javascript-sdk

src/index.js, src/tests/mocks/evolv.mock.js
=> fix: modify getActiveKeys() to return list of previous keys

package-lock.json, package.json, src/webloader.js
Relates to: https://github.com/evolv-ai/javascript-sdk/pull/56
=> feat: rerun changes

src/index.js, src/tests/index.test.js, src/tests/mocks/evolv.mock.js
were not clearing the functions sets, so we were accumulating if the page was not refreshed
RKT-7874
=> fix: previous keys apply

README.md, src/cookies.js, src/tests/mocks/document.mock.js, src/tests/webloader.test.js, src/webloader.js
allow customers to use cookies for uid storage - a domain can be passed in to allow for using apex domain
RKT-7910
=> chore: optional cookies

package-lock.json, package.json, src/guids.js, src/index.js
=> fix: avoid monkey patched Date.now with wrong format

package-lock.json, package.json, src/index.js
=> chore: add reason to contamination

package-lock.json
=> chore: security update

src/tests/index.test.js
=> fix: adding tests

.github/workflows/nightly.yml
move back to nightly runs now passing
=> chore: nightly tests

src/webloader.js
This is bad form and leaks internal functionality
which creates an undocumented public interface.
RKT-8370
=> feat: wrapping pushState handler in an event

package-lock.json, package.json
update to javascriptsdk that supports this
RKT-8396
=> fix: only confirm on non contmainated cids

e2e/tests/apply-changes/apply-changes.test.ts, src/index.js
This change exposes the variant key as a
property on "this".
RKT-8375
=> feat: passing key to JS variants

src/webloader.js
instance count is always > 0 - revert to previous code
RKT-8506
=> fix: remove un-hit code

src/tests/webloader.test.js, src/webloader.js
=> feat: Allow lazy loading uid if uid is blank or lazyLoadUid attribute is present

src/tests/webloader.test.js, src/webloader.js
=> fix: remove check inside setUid to check if uid exists - RKT-8671

src/webloader.js
=> fix: add check in currentScript to ensure the currentScript is webloader - RKT-8684

src/integrations/ga.js, src/tests/mocks/document.mock.js, src/tests/webloader.test.js, src/webloader.js
=> feat: Add temp ga integration to webloader - RKT-8767

src/integrations/ga.js, src/tests/webloader.test.js, src/webloader.js
=> fix: if passing a uid with lazy flag - check if uid is a valid GA client Id

src/index.js
ensure order with array instead of set
RKT-8738
=> fix: context and variant execution order

src/index.js
unnecessary functions array
RKT-8738
=> fix: simplify

package-lock.json, package.json, src/storage.js, src/tests/storage.test.js, src/tests/webloader.test.js, src/webloader.js
do not allow cookie, local or session storage until consent added
RKT-8822
=> fix: consent config

src/storage.js
=> fix: update comment

src/runner.js
not supported in ie11
[RKT-8830]
=> fix: remove usages of array.find()

src/index.js, src/runner.js, src/tests/runner.test.js
also adds more test cases
[RKT-8830]
=> fix: handle calls to reject() without error

src/runner.js, src/tests/runner.test.js
=> fix: correct entry in level map

src/runner.js, src/tests/runner.test.js
=> fix: hold confirm on readystate functions until after imm/legacy

src/index.js, src/runner.js, src/utils.js, src/webloader.js
=> fix: fix regression for rerun()

src/helpers.js, src/runner.js, src/tests/runner.test.js, support/dev/sites/basic/index.html
=> feat: support for "Wait for Elements"

.github/workflows/nightly.yml, .github/workflows/on-deployment.yml, .github/workflows/on-pull.yml, .github/workflows/on-push.yml, package-lock.json, package.json, src/helpers.js, src/tests/mocks/jsdom.js, src/tests/runner.test.js
[RKT-8750]
[RKT-8750]: https://evolvai.atlassian.net/browse/RKT-8750
=> test: tests for wait-for-elements functions

package-lock.json, package.json
[RKT-8873]
[RKT-8873]: https://evolvai.atlassian.net/browse/RKT-8873
=> chore: bump version of javascript-sdk

src/webloader.js
hotfix-v1.8
Fix for when there are multiple webloaders. Used to resolve Bouygues issue.
=> feat: moved markConsent to below checkInstanceCount

src/runner.js, src/tests/mocks/document.mock.js, src/tests/runner.test.js, support/dev/sites/basic/late-loading.html
[RKT-8960]
[RKT-8960]: https://evolvai.atlassian.net/browse/RKT-8960
=> fix: initialize runner.runLevel using document.readyState

e2e/helpers/index.ts, e2e/helpers/skip-if-ie.ts, e2e/helpers/wait-until-loaded.ts, e2e/tests/timing/dom-content-loaded.html, e2e/tests/timing/dom-content-loaded.test.ts, e2e/tests/timing/immediate.html, e2e/tests/timing/immediate.test.ts, e2e/tests/timing/legacy.html, e2e/tests/timing/legacy.test.ts, e2e/tests/timing/loaded.html, e2e/tests/timing/loaded.test.ts
[RKT-9007]
[RKT-9007]: https://evolvai.atlassian.net/browse/RKT-9007
=> test(e2e): tweak waits in end-to-end tests for timing

e2e/tests/timing/legacy.test.ts
it is too flaky to rely on
[RKT-9007]
[RKT-9007]: https://evolvai.atlassian.net/browse/RKT-9007
=> test: skip legacy timing test

package-lock.json, package.json, src/index.js, src/runner.js
Check test coverage with 'npm run coverage'
=> chore: added instanbul

src/webloader.js
[AP-311]
[AP-311]: https://evolv-ai.atlassian.net/browse/AP-311
=> fix: correct custom event ponyfill for pushstate handler

rollup.config.js
m-dash appears different characters in output
=> build: replace m-dash with hyphen in copyright

.editorconfig, src/all.js, src/cookies.js, src/guards.js, src/guids.js, src/helpers.js, src/index.js, src/integrations/ga.js, src/modes/block.mode.js, src/modes/index.js, src/modes/qa.mode.js, src/modes/tests/block.mode.test.js, src/modes/tests/qa.mode.test.js, src/runner.js, src/storage.js, src/tests/all.test.js, src/tests/deferred-promise.js, src/tests/index.test.js, src/tests/mocks/document.mock.js, src/tests/mocks/evolv.mock.js, src/tests/mocks/jsdom.js, src/tests/runner.test.js, src/tests/setup.js, src/tests/storage.test.js, src/tests/wait.js, src/tests/webloader.test.js, src/utils.js, src/webloader.js
allows each dev to set indent size
=> chore(style): convert to tabs

package-lock.json, package.json, src/bootstrap.js, src/build-config.js, src/shims/object-assign.js, src/tests/build-config.test.js, src/webloader.js
[AP-361]
[AP-361]: https://evolv-ai.atlassian.net/browse/AP-361
=> feat: configure based on script.dataset or config object

src/build-config.js
[AP-361]
[AP-361]: https://evolv-ai.atlassian.net/browse/AP-361
=> fix: use let instead of const in for-in loop

package-lock.json, package.json
[AP-490]
[AP-490]: https://evolv-ai.atlassian.net/browse/AP-490
=> fix: bump version of javascript-sdk to 1.13.2

e2e/tests/timing/dom-content-loaded.test.ts, e2e/tests/timing/immediate.test.ts, e2e/tests/timing/loaded.test.ts
[AP-490]
[AP-490]: https://evolv-ai.atlassian.net/browse/AP-490
=> tests: update tests to reflect async xhr requests

src/bootstrap.js, src/fired-events.js, src/tests/fired-event.test.js, src/tests/mocks/evolv.mock.js
https://user-images.githubusercontent.com/18535332/148220589-1cf756a4-235e-4936-a999-858097cb806b.mov
=> feat(ap-907): storing fired events in storage and local context

package-lock.json, package.json, src/bootstrap.js, src/modes/index.js, src/modes/preview.mode.js, src/utils/inject-script.js, src/utils/inject-stylesheet.js, src/utils/tests/inject-script.test.js, src/utils/tests/inject-stylesheet.test.js
[AP-773]
[AP-773]: https://evolv-ai.atlassian.net/browse/AP-773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(AP-773): support hooks for modifying http requests

package-lock.json, package.json
=> AP-1068 browser stack is dev only, and breaks e2e if changed

package-lock.json, package.json
[AP-1446](https://evolv-ai.atlassian.net/browse/AP-1446)
=> chore(deps): dependabot alerts

package-lock.json, package.json
Now we have 0 security vulnerabilities 🕺
=> fix(AP-1655): fix vulnerabilities

package-lock.json, package.json
I used nvm use first. So, I expect the changes in `package.json.lock` file is necessary.
=> fix(ap-1847): updating mutate library

package-lock.json, package.json
Bumping mutate library to the latest
=> Bump mutate library to the latest

package-lock.json, package.json
Trying to see if deployment will succeed with the same code it succeeded last time
=> Revert latest changes

package-lock.json, package.json
Bump mutate library to the [latest](https://www.npmjs.com/package/@evolv/mutate)
=> Bump mutate

package-lock.json, package.json
Update client to version that adds the time info
=> feat: AP-2563 update client to timing client

package-lock.json
[AP-2511](https://evolv-ai.atlassian.net/browse/AP-2511)
[AP-2511]: https://evolv-ai.atlassian.net/browse/AP-2511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ap-2511): security updates

package-lock.json, package.json
=> chore: update mutate

package-lock.json, package.json
New client version v2.4.11-alpha-32f7967
=> feat(AP-2019): Increment JavaScript SDK version

src/bootstrap.js
(No Ticket)
Rolling back a hotfix needed for DirectTV
=> fix: rollback direct tv hotfix

src/bootstrap.js
=> chore: change the message if we try to instantiate ssr twice

package-lock.json, package.json
=> feat: update mutate

package-lock.json, package.json
=> fix: update client

package-lock.json, package.json
=> feat: switch to client that uses GET instead of POST by default

package-lock.json, package.json
=> fix: update mutate

.github/workflows/nightly.yml, .github/workflows/scheduled-deployment.yml
fire failures into general failure channel
=> chore: deploy master, not latest tag

package-lock.json, package.json
=> fix: bump mutate

package-lock.json, package.json
=> chore: update client

e2e/launcher/browsers.js, e2e/launcher/run-tests.js, e2e/launcher/start.js, package-lock.json, package.json, scripts/e2e-test.sh
no value to it
Update the e2e nightly tests to use a headless browser
=> chore: remove browserstack

package-lock.json, package.json
we will now send back web.url changes
=> feat: update dom capture

package-lock.json, package.json
Reverts evolv-ai/asset-manager#434
=> Revert "chore: update mutate version"

.github/workflows/escalated-cherry-pick.yml, .github/workflows/on-push.yml
[AP-5717]
[AP-5717]: https://evolv-ai.atlassian.net/browse/AP-5717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: update the github actions code to use latest

.github/workflows/escalated-cherry-pick.yml, .github/workflows/on-push.yml, README.md
[AP-5717]
[AP-5717]: https://evolv-ai.atlassian.net/browse/AP-5717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: noop change to test the workflows

.github/workflows/escalated-cherry-pick.yml, .github/workflows/on-push.yml
move tagging to master in github actions
=> Action update

README.md
[AP-5717]
[AP-5717]: https://evolv-ai.atlassian.net/browse/AP-5717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: change to test cherrypick

package-lock.json, package.json
occurring when internal confirmations are used instead of normal confirmations
=> fix: update javascript-sdk to prevent an infinite loop

package-lock.json, package.json, src/bootstrap.js
[AP-5802]
[AP-5802]: https://evolv-ai.atlassian.net/browse/AP-5802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: update javascript client to remove events
