evolv-ai/asset-manager

.github/workflows/on-pull-merge.yml
New version of cherry picker allows for activation through comment, and supplies a diff of the new tag vs the previous tag.
=> fix: use version

src/modes/qa.mode.js
RKT-7588
The problem is that ES6 template strings is not supported by IE. I've just changed it to simple string concatenation.
Please let me know if it would be better to add babel transpilation from ES6 to ES5 to rollup configuration.
=> fix: IE does not supoort template strings

.github/workflows/escalated-merge.yml
workflow needs to exist on master to be registered. testing against changes to this workflow on another branch
=> chore: rename escaleted merge workflow

src/index.js
timeout of 1s is causing experiments to timeout if asset.js is slightly late. Make much larger whilst better fix is constructed
RKT-7747
=> chore: update timeout to 60s

src/index.js
Added sorting keys by its length, so that the shortest length keys execute first.
=> fix: context level should execute before variant level

src/webloader.js
call is only used in web editor to notify electron
=> chore: call failing in IE11

.github/workflows/nightly.yml
removing started slack notification -- it's noise
temp update to run on label creation
=> chore: nightly tests

src/tests/webloader.test.js, src/webloader.js
throw an error if there is an existing snippet loaded. This allows the existing snippet to run correctly
RKT-8506
=> fix: only load one snippet

src/storage.js, src/tests/storage.test.js
Always take the vaalue from the persistent store if it exists.
Without this change, uid and sid and replaced every refresh if the consent attribute is set
RKT-8835
=> fix: uid/sid were not persistent once stored

src/runner.js
the script tag onload weirdly fires some time after the script has been parsed and executed. therefore, evolv.javascript.variants can be defined before loadFunctions() is called via the script.onload handler, leading to inconsistent state
[RKT-8750]
=> fix: change gate check on updateFunctionsToRun()

src/index.js, src/tests/index.test.js
This allows the variant JS to reapply when coming back to a page in the context.
=> feat: removed check for liveContexts.length RKT-9004

src/integrations/ga.js, src/tests/webloader.test.js
Ticket: AP-185
Fallback to using Evolv-generated UID if GA client Id is not available.
=> fix: Fallback to generated UID if GA client Id is not available AP-185

src/integrations/ga.js, src/webloader.js
AP-185
Fix: currently, with the fallback UID added if the page is refreshed a new UID is generated. This PR simplifies the process to just running `main()` without the `data-evolv-lazy-uid` attribute, which will behave the same as if a UID is not passed. We generate the UID and store it for when the page refreshes or the user returns.
=> fix: fallback generated uid should persist

src/modes/block.mode.js, src/modes/qa.mode.js, src/webloader.js
[AP-138](https://evolv-ai.atlassian.net/browse/AP-138)
The `evolvBlockExecution` and `evolvCandidateToken` don’t work in case when `data-evolv-require-consent="true"` is present on webloader.js snippet.
=> fix: block and qa modes don't work when consent required

package.json
the bundle currently includes most of the files in the repo including e2e tests and deployment scripts
=> ci: restrict set of files included in package bundle

.github/workflows/nightly.yml, .github/workflows/on-deployment.yml, .github/workflows/on-pull.yml, .github/workflows/on-push.yml, .github/workflows/scheduled-deployment.yml, package-lock.json, package.json
the major difference is that this version uses differential builds (one for node, one for browser)
=> feat(AP-1869): bump version of @evolv/client

package-lock.json, package.json
After pushing last [commit](https://github.com/evolv-ai/asset-manager/pull/296) deployment started failing [link](https://github.com/evolv-ai/asset-manager/actions/runs/3040899139/jobs/4897464932#step:9:405)
In this PR in this PR setting `base64-arraybuffer` version the same as on javascript-sdk (evolv-client) [link](https://github.com/evolv-ai/javascript-sdk/blob/67ed4990b6505312c9a4fcef7d7631c1753199ae/package.json#L61)
=> fix building failure

src/tests/webloader.test.js, src/webloader.js
This PR removes the dnt check client-side as it is a fully deprecated standard and not supported by most products. We can consider implementing it server-side, but client-side enforcement breaks feature flagging and personalization usecases.
=> feat(AP-1917): Removing client-side DNT support

src/asset-manager.js, src/tests/index.test.js, src/tests/mocks/evolv.mock.js
Handle redirect variant on asset-manager.
[AP-1986](https://evolv-ai.atlassian.net/browse/AP-1986)
Changes:
- Process redirect variants in asset-manager.js file
- Before processing redirect check if current url is not the same as url for redirecting
- Send confirmation before processing redirect
- handle redirect for all keys (not only web ones)
- Add tests for redirect variants
Testing:
Tested by running asset manager locally and linking it to the codesandbox website
https://user-images.githubusercontent.com/95315222/211435674-eaafa1d4-f2e2-4ea8-96a9-d38c990b4acd.mov
We send confirmation before redirecting:
https://user-images.githubusercontent.com/95315222/213012828-6b355328-d918-4809-8fd3-8f4b832177f4.mov
Handle redirect with promise: …
=> Handle redirect variants

src/asset-manager.js
[AP-2274](https://evolv-ai.atlassian.net/browse/AP-2274)
Issue:
Fixing the issue when redirect was not working. 
It is possible that the keys for redirect is added to the `activeKeys` later on . 
Solution:
Let runRedirectVariants function run as much as it needs in order to handle the keys that is added later.
[AP-2274]: https://evolv-ai.atlassian.net/browse/AP-2274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://user-images.githubusercontent.com/95315222/216442434-4ab11329-67a6-4a2d-89da-78d290e17a08.mov
=> AP-2274: fix redirect when new keys has arrived later

src/bootstrap.js
Adds ability for a server-side rendered page, such as one using the NextJS SDK, to indicate that it will be responsible for instantiating the Evolv client
=> fix(AP-2793): add coexistence mode with ssr

src/bootstrap.js
this incorrectly turned on by a client. setting it to be ignored
=> fix: ignore ssr

src/bootstrap.js, src/utils/inject-stylesheet.js, src/utils/tests/inject-stylesheet.test.js
it looks timing related - as it doesn't happen if we load a little later. Likely React wiping the dom of changes
This change adds a mutation observer to the parent of the css file. then removes it after 10s
AP-2244
=> fix: some sites remove our css file

src/asset-manager.js, src/tests/index.test.js, src/tests/mocks/document.mock.js, src/tests/webloader.test.js
this will allow web editor to read if the assets js has been loaded/doesn't need to be
This is required to allow us to wait until integrations have run
AP-3414
=> fix: add a dataset attribute for js load

src/asset-manager.js, src/bootstrap.js, src/tests/index.test.js
=> fix: was detecting existence of the script -- not if it had loaded

src/build-config.js, src/tests/build-config.test.js
The config value must be a boolean or a number. Currently it's just interpreted as a string, which won't function properly
=> fix: allow dom capture data tags

e2e/helpers/build-request-hooks.ts
So we don't pick up the error from using GET requests and pointing at prod which does not support them
=> fix: Mock the data and events request

src/webloader-capture.js
Makes it so that we don't have to write a typo in the snippet
=> fix: webloader-capture typo

src/asset-manager.js, src/runner.js, src/tests/runner.test.js
Updated solution to not confirming when you have `evolv:previewCid` set in session storage.
This update checks for the storage item inside the `runner` that runs automatically when the webloader executes. It prevents confirmations when the item is found.
Because I only changed the runner, you can manually confirm into the project if you decide to by running `evolv.client.confirm()`. I think it's important to maintain that flexibility.
=> fix(AP-3821): Prevent auto-confirmation when using previewCid

src/asset-manager.js, src/bootstrap.js, src/build-config.js, src/runner.js
[AP-4079](https://evolv-ai.atlassian.net/browse/AP-4079)
- Added `data-evolv-debug` attribute.
When set to `true`, all contaminations report a stack trace of the error.
[This test page](https://ne2ct.csb.app/page1.html) has experiment running with an error in the context.
```
<script
src="webloader.js"
data-evolv-endpoint="https://participants-stg.evolv.ai"
data-evolv-environment="e6ac170eb9"
data-evolv-debug="true"
></script>
```
[AP-4079]: https://evolv-ai.atlassian.net/browse/AP-4079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(AP-4079): Add debug data attribute

src/modes/preview.mode.js
[AP-5739]
bonus: fixes a bug where we would replace the leading "#" with a "?" if
there were multiple hash params and the preview one was first.
[AP-5739]: https://evolv-ai.atlassian.net/browse/AP-5739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(AP-5739): Support query params for preview links
